# Generated by Django 3.2.23 on 2024-02-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('Publication_year', models.IntegerField()),
                ('review', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
